// <auto-generated />
using System;
using FaceDetector.Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FaceDetector.Domain.Migrations
{
    [DbContext(typeof(FaceAppDbContext))]
    partial class FaceAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FaceDetector.Abstractions.Entities.BaseUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId")
                        .IsUnique()
                        .HasFilter("[CreatedId] IS NOT NULL");

                    b.HasIndex("UpdatedId");

                    b.ToTable("BaseUser");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseUser");
                });

            modelBuilder.Entity("FaceDetector.Domain.Models.Entities.FaceAppImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalyzeResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedId")
                        .HasColumnType("int");

                    b.Property<string>("FileExtension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ImageBase64Length")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PictureHeight")
                        .HasColumnType("int");

                    b.Property<int?>("PictureWidth")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedId");

                    b.HasIndex("UpdatedId");

                    b.ToTable("Faces");
                });

            modelBuilder.Entity("FaceDetector.Domain.Models.Entities.User", b =>
                {
                    b.HasBaseType("FaceDetector.Abstractions.Entities.BaseUser");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("FaceDetector.Abstractions.Entities.BaseUser", b =>
                {
                    b.HasOne("FaceDetector.Abstractions.Entities.BaseUser", "CreatedBy")
                        .WithOne()
                        .HasForeignKey("FaceDetector.Abstractions.Entities.BaseUser", "CreatedId");

                    b.HasOne("FaceDetector.Abstractions.Entities.BaseUser", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedId");
                });

            modelBuilder.Entity("FaceDetector.Domain.Models.Entities.FaceAppImage", b =>
                {
                    b.HasOne("FaceDetector.Abstractions.Entities.BaseUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedId");

                    b.HasOne("FaceDetector.Abstractions.Entities.BaseUser", "LastUpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedId");
                });
#pragma warning restore 612, 618
        }
    }
}
